version: 2.1

orbs:
  docker: circleci/docker@1.0.0


jobs:
  pipenv-unittest:
    description: Run Unit Tests via Pipenv
    docker:
      - image: kennethreitz/pipenv
    steps:
      - checkout
      - pipenv sync
      - pipenv check
      - pipenv run python -m unittest


workflows:
  version: 2

  tests:
    jobs:
      - pipenv-unittest

  publish:
    requires:
      - tests
    filters:
      branches:
        only: master
    jobs:
      - docker/publish:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
          lint-dockerfile: true

